### ISSUE TITLE
Installation from file

### ISSUE THREAD

**Issue by MarcRohrer** [Bogdanp/racket-net-mime-type#2]
Hi,

I installed mime-type-lib from the downloaded file (necessary behind proxy server)
with raco pkg install --scope installation racket-net-mime-type-master.zip
There is tons of errors then.

I remember when I installed it at home with the package manager downloading it,
there also was an error, but it worked afterwards. At work I get:

; h:\src\racket\server.rkt:12:9: cannot open module file
;   module path: net/mime-type
;   path: c:\Program Files\Racket\collects\net\mime-type.rkt
;   system error: no such file or directory; rkt_err=3

What is the problem, or better, how to solve it :-)
Hope to be a regular user in the future!
Thanx!

Marc

**Comment by MarcRohrer** [comment]
Here ist the installation transcript:

C:\Temp>raco pkg install --scope installation racket-net-mime-type-master.zip
raco setup: version: 8.8
raco setup: platform: win32\x86_64 [cs]
raco setup: target machine: ta6nt
raco setup: installation name: 8.8
raco setup: variants: cs
raco setup: main collects: C:\Program Files\Racket\collects\
raco setup: collects paths:
raco setup:   C:\Program Files\Racket\collects\
raco setup: main pkgs: C:\Program Files\Racket\share\pkgs
raco setup: pkgs paths:
raco setup:   C:\Program Files\Racket\share\pkgs
raco setup:   C:\Users\sup.rohrerm\AppData\Roaming\Racket\8.8\pkgs
raco setup: links files:
raco setup:   C:\Program Files\Racket\share\links.rktd
raco setup:   C:\Users\sup.rohrerm\AppData\Roaming\Racket\8.8\links.rktd
raco setup: main docs: C:\Program Files\Racket\doc
raco setup: --- updating info-domain tables ---                    [8:40:12]
raco setup: updating: C:\Program Files\Racket\share\info-cache.rktd
raco setup: --- pre-installing collections ---                     [8:40:12]
raco setup: --- installing foreign libraries ---                   [8:40:12]
raco setup: --- installing shared files ---                        [8:40:12]
raco setup: --- compiling collections ---                          [8:40:12]
raco setup: --- parallel build using 8 jobs ---                    [8:40:12]
raco setup: 7 making: <pkgs>/racket-index/scribblings/main
raco setup: 6 making: <pkgs>/racket-net-mime-type-master
raco setup: 6 making: <pkgs>/racket-net-mime-type-master/mime-type
raco setup: 6 making: <pkgs>/racket-net-mime-type-master/mime-type/net
raco setup: 6 making: <pkgs>/racket-net-mime-type-master/mime-type/net/scribblings
raco setup: 6 making: <pkgs>/racket-net-mime-type-master/mime-type/tests
raco setup: 6 making: <pkgs>/racket-net-mime-type-master/mime-type/tests/net
raco setup: 6 making: <pkgs>/racket-net-mime-type-master/mime-type-lib
C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\tests\net\mime-type.rkt:4:11: cannot open module file
  module path: net/mime-type
  path: C:\Program Files\Racket\collects\net\mime-type.rkt
  system error: no such file or directory; rkt_err=3
  compilation context...:
   C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\tests\net\mime-type.rkt
  location...:
   C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\tests\net\mime-type.rkt:4:11
  context...:
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:686:0: compile-zo*
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:452:15
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:441:12: build
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:412:0: maybe-compile-zo
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:210:0: compile-root
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:105:4
   C:\Program Files\Racket\collects\setup\parallel-build.rkt:332:9
   C:\Program Files\Racket\collects\setup\parallel-do.rkt:456:25
   C:\Program Files\Racket\collects\setup\parallel-do.rkt:442:20: loop
raco setup: 7 making: <pkgs>/racket-index/scribblings/main/private
raco setup: 7 making: <pkgs>/racket-index/scribblings/main/user
C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\net\scribblings\mime-type.scrbl:3:21: cannot open module file
  module path: net/mime-type
  path: C:\Program Files\Racket\collects\net\mime-type.rkt
  system error: no such file or directory; rkt_err=3
  compilation context...:
   C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\net\scribblings\mime-type.scrbl
  location...:
   C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\net\scribblings\mime-type.scrbl:3:21
  context...:
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:686:0: compile-zo*
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:452:15
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:441:12: build
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:412:0: maybe-compile-zo
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:210:0: compile-root
   C:\Program Files\Racket\collects\compiler\private\cm-minimal.rkt:105:4
   C:\Program Files\Racket\collects\setup\parallel-build.rkt:332:9
   C:\Program Files\Racket\collects\setup\parallel-do.rkt:456:25
   C:\Program Files\Racket\collects\setup\parallel-do.rkt:442:20: loop
raco setup: --- creating launchers ---                             [8:40:14]
raco setup: --- building documentation ---                         [8:40:14]
raco setup: 7 running: <pkgs>/racket-net-mime-type-master/mime-type/net/scribblings/mime-type.scrbl
C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\net\scribblings\mime-type.scrbl:3:21: cannot open module file
  module path: net/mime-type
  path: C:\Program Files\Racket\collects\net\mime-type.rkt
  system error: no such file or directory; rkt_err=3
  location...:
   C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\net\scribblings\mime-type.scrbl:3:21
  context...:
   C:\Program Files\Racket\share\pkgs\racket-index\setup\scribble.rkt:1567:27

  context...:
   C:\Program Files\Racket\collects\setup\parallel-do.rkt:333:4: work-done method in list-queue%
   C:\Program Files\Racket\collects\setup\parallel-do.rkt:283:17
   C:\Program Files\Racket\collects\setup\parallel-do.rkt:237:4
   C:\Program Files\Racket\share\pkgs\racket-index\setup\scribble.rkt:139:0: setup-scribblings
   C:\Program Files\Racket\collects\setup\setup.rkt:78:3
   C:\Program Files\Racket\collects\pkg\main.rkt:17:0: setup
   body of (submod "C:\Program Files\Racket\collects\pkg\main.rkt" main)
   C:\Program Files\Racket\collects\raco\raco.rkt:41:0
   body of "C:\Program Files\Racket\collects\raco\raco.rkt"
   body of "C:\Program Files\Racket\collects\raco\main.rkt"
raco setup: --- installing collections ---                         [8:40:18]
raco setup: --- post-installing collections ---                    [8:40:18]
raco setup: --- summary of errors ---                              [8:40:18]
raco setup: error: during making for <pkgs>/racket-net-mime-type-master/mime-type/tests/net
raco setup:   C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\tests\net\mime-type.rkt:4:11: cannot open module file
raco setup:     module path: net/mime-type
raco setup:     path: C:\Program Files\Racket\collects\net\mime-type.rkt
raco setup:     system error: no such file or directory; rkt_err=3
raco setup:     compiling: <pkgs>/racket-net-mime-type-master/mime-type/tests/net/mime-type.rkt
raco setup: error: during making for <pkgs>/racket-net-mime-type-master/mime-type/net/scribblings
raco setup:   C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\net\scribblings\mime-type.scrbl:3:21: cannot open module file
raco setup:     module path: net/mime-type
raco setup:     path: C:\Program Files\Racket\collects\net\mime-type.rkt
raco setup:     system error: no such file or directory; rkt_err=3
raco setup:     compiling: <pkgs>/racket-net-mime-type-master/mime-type/net/scribblings/mime-type.scrbl
raco setup: error: during building docs for <pkgs>/racket-net-mime-type-master/mime-type/net/scribblings/mime-type.scrblraco setup:   C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\net\scribblings\mime-type.scrbl:3:21: cannot open module file
raco setup:     module path: net/mime-type
raco setup:     path: C:\Program Files\Racket\collects\net\mime-type.rkt
raco setup:     system error: no such file or directory; rkt_err=3
raco setup:     location...:
raco setup:      C:\Program Files\Racket\share\pkgs\racket-net-mime-type-master\mime-type\net\scribblings\mime-type.scrbl:3:21
raco setup:     context...:
raco setup:      C:\Program Files\Racket\share\pkgs\racket-index\setup\scribble.rkt:1567:27
raco setup:
raco pkg install: packages installed, although setup reported errors

C:\Temp>

**Comment by Bogdanp** [comment]
If you plan to install from source, you'll have to unzip the archive and install the `mime-type-lib` and `mime-type` packages separately:

```
$ unzip racket-net-mime-type-master.zip
$ raco pkg install mime-type-lib/ # the forward slash is important!
$ raco pkg install mime-type/
```

See [this doc](https://docs.racket-lang.org/pkg/Package_Concepts.html#%28tech._package._source%29) for more info.

**Comment by MarcRohrer** [comment]
Hi Bogdan,

thanx for the info. I only wanted to install the library. 
Running behind a proxy server, there is not much information, how to do it.

I was missing the information, that this is an "installation from source".

I am quite new to th racket ecosystem, so please forgive me my dumb queston.

Thanx again!

Marc

**Comment by Bogdanp** [comment]
No worries, it's not a dumb question. Were you able to install the package using those instructions?

**Comment by MarcRohrer** [comment]
Hi Bogdan,

I will try it on Monday. Thanx! 

Marc

**Comment by MarcRohrer** [comment]
Hi Bogdan,

it almost worked, running from the folder, where the direcories reside.
mime-type-lib installs seamlessly, but trying to install mime-type/ I get
the error:

----
C:\Temp\racket-net-mime-type-master>raco pkg install --scope installation mime-type/
raco pkg install: package conflicts with existing installed item
  package: mime-type/
  item category: doc
  item name: "mime-type"
----

I was wondering why there are these problems anyway? I also installed dotenv
and response-ext, which worked out of the box (installed from the zip file).
What is the dirrerence?

But the the program seams to run anyway now...

Thanx for your help!

Marc
